### ISSUE TITLE
Motifs of pathogenic repeats

### ISSUE THREAD

**Issue by Jong-hun-Park** [ACEnglish/adotto#3]
Hi Adam,

In [Patho.tsv](https://github.com/ACEnglish/adotto/blob/main/pathogenic/Patho.tsv), I've noticed that some pathogenic repeats 

1. do not have motif information (e.g. chr13:102161577-102161726, FGF14) OR
2. have only motif2 (e.g. chr1:146228800-146228822, NOTCH2NLA) OR
3. have the same motif in motif1 and motif2 column (e.g. chr10:79826383-79826404, NUTM2B-AS1, CGG, CGG)

It seems that the motif for FGF14 TR is "GAA" based on [this paper](https://pubmed.ncbi.nlm.nih.gov/36493768/). It might be dropped for some reason when compiling that information.
For 2 and 3, can you please clarify the meaning of the motif1 and motif2 columns?

Thanks,
Jonghun

**Comment by ACEnglish** [comment]
THAP11 and FGF14 were just recently added from two new papers. I recently put in the motifs but forgot to push the changes (fixed now).
I can't remember exactly the difference between motif1/motif2 - but they coincide with the whichever of the two original pathogenic sources we partially consolidated via (see [STRipy_scrape.ipynb](https://github.com/ACEnglish/adotto/blob/main/pathogenic/STRipy_scrape.ipynb)). 
If they have the same motif1/2, that's because the sources agreed. If they have different, they were reported differently.

**Comment by Jong-hun-Park** [comment]
Got it. Thanks!
